apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: giropops2
  name: giropops2
spec:
  containers:
  - image: nginx
    name: giropops2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
